#cloud-config
package_update: true
package_upgrade: true
packages:
  - apache2
  - git
  - php5
  - mysql-server
  - php5-mysql
  - php5-apcu
  - php5-gd
  - php5-intl
runcmd:
  - ["cd","/tmp"]
  - ["git","clone","https://github.com/cgeroux/cloud-init-mediawiki.git"]
  - ["/tmp/cloud-init-mediawiki/mediawiki-setup.py", "--wik-version","WIKIVERSION","--wiki-patch","WIKIPATCH","--name","WIKINAME","--read-permission","READPERMISSION","--edit-permission","EDITPERMISSION","--account-create-permission","ACCCREATEPERMISSION","--admin-user","ADMINUSER","UPLOADS","SERVERADDRESS"]
