#cloud-config
package_update: true
package_upgrade: true
packages:
  - apache2
runcmd:
  - ["wget","https://raw.githubusercontent.com/cgeroux/apache-cloud-init/master/setup.py","/tmp/setup.py"]
  - ["/tmp/setup.py"]
  - ["rm","/tmp/setup.py"]