#cloud-config
package_update: true
package_upgrade: true
packages:
  - apache2
runcmd:
  - ["wget","https://raw.githubusercontent.com/cgeroux/cloud-init-mediawiki/master/mediawiki-setup.py","/tmp/mediawiki-setup.py"]
  - ["/tmp/mediawiki-setup.py"]
  - ["rm","/tmp/mediawiki-setup.py"]